spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false

jwt:
  secret: EowDYBudW1TTb6XJ5uh77yYYAgxhMa2/4DLyekvR2+sf+J3OS/bBvmsz7A2O9sNq0Xc9Ehhg4dDSPBAjqQ6HUA==
  expiration: 86400000

graph:
  file:
    path: grafo.txt