services:

  mysql:
    image: mysql:8.4
    container_name: careergraph_mysql

    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: careergraph

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin123" ]
      timeout: 5s
      retries: 5
      start_period: 15s

  backend:
    build: ./careergraph
    container_name: careergraph_backend

    ports:
      - "8080:8080"

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/careergraph
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123

  frontend:
    build: ./frontend
    container_name: careergraph_frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

volumes:
  mysql_data: